# Generated by Django 3.2.7 on 2021-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lat',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
