# Generated by Django 3.2.7 on 2021-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='qr_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
