# Generated by Django 3.2.7 on 2021-10-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_qr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='long',
        ),
    ]
