# Generated by Django 3.2.7 on 2021-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211007_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='frequency',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='reasonOfVisit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='stars',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
