# Generated by Django 3.2.7 on 2021-10-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211026_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='safety',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
