# Generated by Django 3.2.7 on 2021-11-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_feedback_qr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='qr_id',
            field=models.CharField(max_length=100),
        ),
    ]
